// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public class AutoConfigResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject autoConfigResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.AutoConfigResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		End_session_endpoint("End_session_endpoint"),
		Authorization_endpoint("Authorization_endpoint"),
		Token_endpoint("Token_endpoint"),
		Revocation_endpoint("Revocation_endpoint"),
		Userinfo_endpoint("Userinfo_endpoint"),
		Jwks_uri("Jwks_uri"),
		Registration_endpoint("Registration_endpoint"),
		Introspection_endpoint("Introspection_endpoint"),
		Issuer("Issuer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AutoConfigResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AutoConfigResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject autoConfigResponseMendixObject)
	{
		if (autoConfigResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, autoConfigResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.autoConfigResponseMendixObject = autoConfigResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AutoConfigResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.AutoConfigResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.AutoConfigResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.AutoConfigResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.AutoConfigResponse(context, mendixObject);
	}

	public static oidc.proxies.AutoConfigResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.AutoConfigResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of End_session_endpoint
	 */
	public final java.lang.String getEnd_session_endpoint()
	{
		return getEnd_session_endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of End_session_endpoint
	 */
	public final java.lang.String getEnd_session_endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.End_session_endpoint.toString());
	}

	/**
	 * Set value of End_session_endpoint
	 * @param end_session_endpoint
	 */
	public final void setEnd_session_endpoint(java.lang.String end_session_endpoint)
	{
		setEnd_session_endpoint(getContext(), end_session_endpoint);
	}

	/**
	 * Set value of End_session_endpoint
	 * @param context
	 * @param end_session_endpoint
	 */
	public final void setEnd_session_endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String end_session_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.End_session_endpoint.toString(), end_session_endpoint);
	}

	/**
	 * @return value of Authorization_endpoint
	 */
	public final java.lang.String getAuthorization_endpoint()
	{
		return getAuthorization_endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Authorization_endpoint
	 */
	public final java.lang.String getAuthorization_endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Authorization_endpoint.toString());
	}

	/**
	 * Set value of Authorization_endpoint
	 * @param authorization_endpoint
	 */
	public final void setAuthorization_endpoint(java.lang.String authorization_endpoint)
	{
		setAuthorization_endpoint(getContext(), authorization_endpoint);
	}

	/**
	 * Set value of Authorization_endpoint
	 * @param context
	 * @param authorization_endpoint
	 */
	public final void setAuthorization_endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authorization_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Authorization_endpoint.toString(), authorization_endpoint);
	}

	/**
	 * @return value of Token_endpoint
	 */
	public final java.lang.String getToken_endpoint()
	{
		return getToken_endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_endpoint
	 */
	public final java.lang.String getToken_endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_endpoint.toString());
	}

	/**
	 * Set value of Token_endpoint
	 * @param token_endpoint
	 */
	public final void setToken_endpoint(java.lang.String token_endpoint)
	{
		setToken_endpoint(getContext(), token_endpoint);
	}

	/**
	 * Set value of Token_endpoint
	 * @param context
	 * @param token_endpoint
	 */
	public final void setToken_endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Token_endpoint.toString(), token_endpoint);
	}

	/**
	 * @return value of Revocation_endpoint
	 */
	public final java.lang.String getRevocation_endpoint()
	{
		return getRevocation_endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Revocation_endpoint
	 */
	public final java.lang.String getRevocation_endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revocation_endpoint.toString());
	}

	/**
	 * Set value of Revocation_endpoint
	 * @param revocation_endpoint
	 */
	public final void setRevocation_endpoint(java.lang.String revocation_endpoint)
	{
		setRevocation_endpoint(getContext(), revocation_endpoint);
	}

	/**
	 * Set value of Revocation_endpoint
	 * @param context
	 * @param revocation_endpoint
	 */
	public final void setRevocation_endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revocation_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Revocation_endpoint.toString(), revocation_endpoint);
	}

	/**
	 * @return value of Userinfo_endpoint
	 */
	public final java.lang.String getUserinfo_endpoint()
	{
		return getUserinfo_endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Userinfo_endpoint
	 */
	public final java.lang.String getUserinfo_endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Userinfo_endpoint.toString());
	}

	/**
	 * Set value of Userinfo_endpoint
	 * @param userinfo_endpoint
	 */
	public final void setUserinfo_endpoint(java.lang.String userinfo_endpoint)
	{
		setUserinfo_endpoint(getContext(), userinfo_endpoint);
	}

	/**
	 * Set value of Userinfo_endpoint
	 * @param context
	 * @param userinfo_endpoint
	 */
	public final void setUserinfo_endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userinfo_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Userinfo_endpoint.toString(), userinfo_endpoint);
	}

	/**
	 * @return value of Jwks_uri
	 */
	public final java.lang.String getJwks_uri()
	{
		return getJwks_uri(getContext());
	}

	/**
	 * @param context
	 * @return value of Jwks_uri
	 */
	public final java.lang.String getJwks_uri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Jwks_uri.toString());
	}

	/**
	 * Set value of Jwks_uri
	 * @param jwks_uri
	 */
	public final void setJwks_uri(java.lang.String jwks_uri)
	{
		setJwks_uri(getContext(), jwks_uri);
	}

	/**
	 * Set value of Jwks_uri
	 * @param context
	 * @param jwks_uri
	 */
	public final void setJwks_uri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jwks_uri)
	{
		getMendixObject().setValue(context, MemberNames.Jwks_uri.toString(), jwks_uri);
	}

	/**
	 * @return value of Registration_endpoint
	 */
	public final java.lang.String getRegistration_endpoint()
	{
		return getRegistration_endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Registration_endpoint
	 */
	public final java.lang.String getRegistration_endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Registration_endpoint.toString());
	}

	/**
	 * Set value of Registration_endpoint
	 * @param registration_endpoint
	 */
	public final void setRegistration_endpoint(java.lang.String registration_endpoint)
	{
		setRegistration_endpoint(getContext(), registration_endpoint);
	}

	/**
	 * Set value of Registration_endpoint
	 * @param context
	 * @param registration_endpoint
	 */
	public final void setRegistration_endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String registration_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Registration_endpoint.toString(), registration_endpoint);
	}

	/**
	 * @return value of Introspection_endpoint
	 */
	public final java.lang.String getIntrospection_endpoint()
	{
		return getIntrospection_endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Introspection_endpoint
	 */
	public final java.lang.String getIntrospection_endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Introspection_endpoint.toString());
	}

	/**
	 * Set value of Introspection_endpoint
	 * @param introspection_endpoint
	 */
	public final void setIntrospection_endpoint(java.lang.String introspection_endpoint)
	{
		setIntrospection_endpoint(getContext(), introspection_endpoint);
	}

	/**
	 * Set value of Introspection_endpoint
	 * @param context
	 * @param introspection_endpoint
	 */
	public final void setIntrospection_endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String introspection_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Introspection_endpoint.toString(), introspection_endpoint);
	}

	/**
	 * @return value of Issuer
	 */
	public final java.lang.String getIssuer()
	{
		return getIssuer(getContext());
	}

	/**
	 * @param context
	 * @return value of Issuer
	 */
	public final java.lang.String getIssuer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Issuer.toString());
	}

	/**
	 * Set value of Issuer
	 * @param issuer
	 */
	public final void setIssuer(java.lang.String issuer)
	{
		setIssuer(getContext(), issuer);
	}

	/**
	 * Set value of Issuer
	 * @param context
	 * @param issuer
	 */
	public final void setIssuer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issuer)
	{
		getMendixObject().setValue(context, MemberNames.Issuer.toString(), issuer);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return autoConfigResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.AutoConfigResponse that = (oidc.proxies.AutoConfigResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
