// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public class ClientConfigHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject clientConfigHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.ClientConfigHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UnencryptedClientSecret("UnencryptedClientSecret"),
		ShowSecret("ShowSecret"),
		ClientConfigHelper_ClientConfiguration("OIDC.ClientConfigHelper_ClientConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ClientConfigHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ClientConfigHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject clientConfigHelperMendixObject)
	{
		if (clientConfigHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, clientConfigHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.clientConfigHelperMendixObject = clientConfigHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ClientConfigHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.ClientConfigHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.ClientConfigHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.ClientConfigHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.ClientConfigHelper(context, mendixObject);
	}

	public static oidc.proxies.ClientConfigHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.ClientConfigHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UnencryptedClientSecret
	 */
	public final java.lang.String getUnencryptedClientSecret()
	{
		return getUnencryptedClientSecret(getContext());
	}

	/**
	 * @param context
	 * @return value of UnencryptedClientSecret
	 */
	public final java.lang.String getUnencryptedClientSecret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UnencryptedClientSecret.toString());
	}

	/**
	 * Set value of UnencryptedClientSecret
	 * @param unencryptedclientsecret
	 */
	public final void setUnencryptedClientSecret(java.lang.String unencryptedclientsecret)
	{
		setUnencryptedClientSecret(getContext(), unencryptedclientsecret);
	}

	/**
	 * Set value of UnencryptedClientSecret
	 * @param context
	 * @param unencryptedclientsecret
	 */
	public final void setUnencryptedClientSecret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unencryptedclientsecret)
	{
		getMendixObject().setValue(context, MemberNames.UnencryptedClientSecret.toString(), unencryptedclientsecret);
	}

	/**
	 * @return value of ShowSecret
	 */
	public final java.lang.Boolean getShowSecret()
	{
		return getShowSecret(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowSecret
	 */
	public final java.lang.Boolean getShowSecret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowSecret.toString());
	}

	/**
	 * Set value of ShowSecret
	 * @param showsecret
	 */
	public final void setShowSecret(java.lang.Boolean showsecret)
	{
		setShowSecret(getContext(), showsecret);
	}

	/**
	 * Set value of ShowSecret
	 * @param context
	 * @param showsecret
	 */
	public final void setShowSecret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showsecret)
	{
		getMendixObject().setValue(context, MemberNames.ShowSecret.toString(), showsecret);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ClientConfigHelper_ClientConfiguration
	 */
	public final oidc.proxies.ClientConfiguration getClientConfigHelper_ClientConfiguration() throws com.mendix.core.CoreException
	{
		return getClientConfigHelper_ClientConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientConfigHelper_ClientConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final oidc.proxies.ClientConfiguration getClientConfigHelper_ClientConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oidc.proxies.ClientConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ClientConfigHelper_ClientConfiguration.toString());
		if (identifier != null) {
			result = oidc.proxies.ClientConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ClientConfigHelper_ClientConfiguration
	 * @param clientconfighelper_clientconfiguration
	 */
	public final void setClientConfigHelper_ClientConfiguration(oidc.proxies.ClientConfiguration clientconfighelper_clientconfiguration)
	{
		setClientConfigHelper_ClientConfiguration(getContext(), clientconfighelper_clientconfiguration);
	}

	/**
	 * Set value of ClientConfigHelper_ClientConfiguration
	 * @param context
	 * @param clientconfighelper_clientconfiguration
	 */
	public final void setClientConfigHelper_ClientConfiguration(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.ClientConfiguration clientconfighelper_clientconfiguration)
	{
		if (clientconfighelper_clientconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.ClientConfigHelper_ClientConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ClientConfigHelper_ClientConfiguration.toString(), clientconfighelper_clientconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return clientConfigHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.ClientConfigHelper that = (oidc.proxies.ClientConfigHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
