// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

/**
 * Represents a single OIDC client registration.
 */
public class ClientConfiguration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject clientConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.ClientConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Alias("Alias"),
		ClientID("ClientID"),
		ClientAssertion("ClientAssertion"),
		EncryptedClientSecret("EncryptedClientSecret"),
		IsDefault("IsDefault"),
		Active("Active"),
		WellKnownConfigUri("WellKnownConfigUri"),
		AuthorizationEndpoint("AuthorizationEndpoint"),
		TokenEndpoint("TokenEndpoint"),
		UserInfoEndpoint("UserInfoEndpoint"),
		EndSessionEndpoint("EndSessionEndpoint"),
		JWKSUri("JWKSUri"),
		Issuer("Issuer"),
		ProvisioningFlow("ProvisioningFlow"),
		ResponseMode("ResponseMode"),
		UsePCKE("UsePCKE"),
		CustomCallbackURL("CustomCallbackURL"),
		parseroles("parseroles"),
		ClientAuthenticationMethod("ClientAuthenticationMethod"),
		SelectedScopes("OIDC.SelectedScopes"),
		ClientConfiguration_ScopeSet("OIDC.ClientConfiguration_ScopeSet"),
		ClientConfiguration_ClaimSet("OIDC.ClientConfiguration_ClaimSet"),
		SelectedClaims("OIDC.SelectedClaims"),
		ClientConfiguration_CodeChallengeMethodsSet("OIDC.ClientConfiguration_CodeChallengeMethodsSet"),
		ClientConfiguration_CodeChallengeMethods("OIDC.ClientConfiguration_CodeChallengeMethods"),
		ClientConfiguration_Microflows("OIDC.ClientConfiguration_Microflows");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ClientConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ClientConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject clientConfigurationMendixObject)
	{
		if (clientConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, clientConfigurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.clientConfigurationMendixObject = clientConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ClientConfiguration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.ClientConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.ClientConfiguration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.ClientConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.ClientConfiguration(context, mendixObject);
	}

	public static oidc.proxies.ClientConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.ClientConfiguration.initialize(context, mendixObject);
	}

	public static java.util.List<oidc.proxies.ClientConfiguration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> oidc.proxies.ClientConfiguration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Alias
	 */
	public final java.lang.String getAlias()
	{
		return getAlias(getContext());
	}

	/**
	 * @param context
	 * @return value of Alias
	 */
	public final java.lang.String getAlias(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alias.toString());
	}

	/**
	 * Set value of Alias
	 * @param alias
	 */
	public final void setAlias(java.lang.String alias)
	{
		setAlias(getContext(), alias);
	}

	/**
	 * Set value of Alias
	 * @param context
	 * @param alias
	 */
	public final void setAlias(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alias)
	{
		getMendixObject().setValue(context, MemberNames.Alias.toString(), alias);
	}

	/**
	 * @return value of ClientID
	 */
	public final java.lang.String getClientID()
	{
		return getClientID(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientID
	 */
	public final java.lang.String getClientID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientID.toString());
	}

	/**
	 * Set value of ClientID
	 * @param clientid
	 */
	public final void setClientID(java.lang.String clientid)
	{
		setClientID(getContext(), clientid);
	}

	/**
	 * Set value of ClientID
	 * @param context
	 * @param clientid
	 */
	public final void setClientID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientid)
	{
		getMendixObject().setValue(context, MemberNames.ClientID.toString(), clientid);
	}

	/**
	 * Set value of ClientAssertion
	 * @param clientassertion
	 */
	public final oidc.proxies.ENU_ClientAssertion getClientAssertion()
	{
		return getClientAssertion(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientAssertion
	 */
	public final oidc.proxies.ENU_ClientAssertion getClientAssertion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ClientAssertion.toString());
		if (obj == null) {
			return null;
		}
		return oidc.proxies.ENU_ClientAssertion.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ClientAssertion
	 * @param clientassertion
	 */
	public final void setClientAssertion(oidc.proxies.ENU_ClientAssertion clientassertion)
	{
		setClientAssertion(getContext(), clientassertion);
	}

	/**
	 * Set value of ClientAssertion
	 * @param context
	 * @param clientassertion
	 */
	public final void setClientAssertion(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.ENU_ClientAssertion clientassertion)
	{
		if (clientassertion != null) {
			getMendixObject().setValue(context, MemberNames.ClientAssertion.toString(), clientassertion.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ClientAssertion.toString(), null);
		}
	}

	/**
	 * @return value of EncryptedClientSecret
	 */
	public final java.lang.String getEncryptedClientSecret()
	{
		return getEncryptedClientSecret(getContext());
	}

	/**
	 * @param context
	 * @return value of EncryptedClientSecret
	 */
	public final java.lang.String getEncryptedClientSecret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EncryptedClientSecret.toString());
	}

	/**
	 * Set value of EncryptedClientSecret
	 * @param encryptedclientsecret
	 */
	public final void setEncryptedClientSecret(java.lang.String encryptedclientsecret)
	{
		setEncryptedClientSecret(getContext(), encryptedclientsecret);
	}

	/**
	 * Set value of EncryptedClientSecret
	 * @param context
	 * @param encryptedclientsecret
	 */
	public final void setEncryptedClientSecret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String encryptedclientsecret)
	{
		getMendixObject().setValue(context, MemberNames.EncryptedClientSecret.toString(), encryptedclientsecret);
	}

	/**
	 * @return value of IsDefault
	 */
	public final java.lang.Boolean getIsDefault()
	{
		return getIsDefault(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDefault
	 */
	public final java.lang.Boolean getIsDefault(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDefault.toString());
	}

	/**
	 * Set value of IsDefault
	 * @param isdefault
	 */
	public final void setIsDefault(java.lang.Boolean isdefault)
	{
		setIsDefault(getContext(), isdefault);
	}

	/**
	 * Set value of IsDefault
	 * @param context
	 * @param isdefault
	 */
	public final void setIsDefault(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdefault)
	{
		getMendixObject().setValue(context, MemberNames.IsDefault.toString(), isdefault);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of WellKnownConfigUri
	 */
	public final java.lang.String getWellKnownConfigUri()
	{
		return getWellKnownConfigUri(getContext());
	}

	/**
	 * @param context
	 * @return value of WellKnownConfigUri
	 */
	public final java.lang.String getWellKnownConfigUri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WellKnownConfigUri.toString());
	}

	/**
	 * Set value of WellKnownConfigUri
	 * @param wellknownconfiguri
	 */
	public final void setWellKnownConfigUri(java.lang.String wellknownconfiguri)
	{
		setWellKnownConfigUri(getContext(), wellknownconfiguri);
	}

	/**
	 * Set value of WellKnownConfigUri
	 * @param context
	 * @param wellknownconfiguri
	 */
	public final void setWellKnownConfigUri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wellknownconfiguri)
	{
		getMendixObject().setValue(context, MemberNames.WellKnownConfigUri.toString(), wellknownconfiguri);
	}

	/**
	 * @return value of AuthorizationEndpoint
	 */
	public final java.lang.String getAuthorizationEndpoint()
	{
		return getAuthorizationEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthorizationEndpoint
	 */
	public final java.lang.String getAuthorizationEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AuthorizationEndpoint.toString());
	}

	/**
	 * Set value of AuthorizationEndpoint
	 * @param authorizationendpoint
	 */
	public final void setAuthorizationEndpoint(java.lang.String authorizationendpoint)
	{
		setAuthorizationEndpoint(getContext(), authorizationendpoint);
	}

	/**
	 * Set value of AuthorizationEndpoint
	 * @param context
	 * @param authorizationendpoint
	 */
	public final void setAuthorizationEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authorizationendpoint)
	{
		getMendixObject().setValue(context, MemberNames.AuthorizationEndpoint.toString(), authorizationendpoint);
	}

	/**
	 * @return value of TokenEndpoint
	 */
	public final java.lang.String getTokenEndpoint()
	{
		return getTokenEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenEndpoint
	 */
	public final java.lang.String getTokenEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TokenEndpoint.toString());
	}

	/**
	 * Set value of TokenEndpoint
	 * @param tokenendpoint
	 */
	public final void setTokenEndpoint(java.lang.String tokenendpoint)
	{
		setTokenEndpoint(getContext(), tokenendpoint);
	}

	/**
	 * Set value of TokenEndpoint
	 * @param context
	 * @param tokenendpoint
	 */
	public final void setTokenEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tokenendpoint)
	{
		getMendixObject().setValue(context, MemberNames.TokenEndpoint.toString(), tokenendpoint);
	}

	/**
	 * @return value of UserInfoEndpoint
	 */
	public final java.lang.String getUserInfoEndpoint()
	{
		return getUserInfoEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of UserInfoEndpoint
	 */
	public final java.lang.String getUserInfoEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserInfoEndpoint.toString());
	}

	/**
	 * Set value of UserInfoEndpoint
	 * @param userinfoendpoint
	 */
	public final void setUserInfoEndpoint(java.lang.String userinfoendpoint)
	{
		setUserInfoEndpoint(getContext(), userinfoendpoint);
	}

	/**
	 * Set value of UserInfoEndpoint
	 * @param context
	 * @param userinfoendpoint
	 */
	public final void setUserInfoEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userinfoendpoint)
	{
		getMendixObject().setValue(context, MemberNames.UserInfoEndpoint.toString(), userinfoendpoint);
	}

	/**
	 * @return value of EndSessionEndpoint
	 */
	public final java.lang.String getEndSessionEndpoint()
	{
		return getEndSessionEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of EndSessionEndpoint
	 */
	public final java.lang.String getEndSessionEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndSessionEndpoint.toString());
	}

	/**
	 * Set value of EndSessionEndpoint
	 * @param endsessionendpoint
	 */
	public final void setEndSessionEndpoint(java.lang.String endsessionendpoint)
	{
		setEndSessionEndpoint(getContext(), endsessionendpoint);
	}

	/**
	 * Set value of EndSessionEndpoint
	 * @param context
	 * @param endsessionendpoint
	 */
	public final void setEndSessionEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endsessionendpoint)
	{
		getMendixObject().setValue(context, MemberNames.EndSessionEndpoint.toString(), endsessionendpoint);
	}

	/**
	 * @return value of JWKSUri
	 */
	public final java.lang.String getJWKSUri()
	{
		return getJWKSUri(getContext());
	}

	/**
	 * @param context
	 * @return value of JWKSUri
	 */
	public final java.lang.String getJWKSUri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JWKSUri.toString());
	}

	/**
	 * Set value of JWKSUri
	 * @param jwksuri
	 */
	public final void setJWKSUri(java.lang.String jwksuri)
	{
		setJWKSUri(getContext(), jwksuri);
	}

	/**
	 * Set value of JWKSUri
	 * @param context
	 * @param jwksuri
	 */
	public final void setJWKSUri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jwksuri)
	{
		getMendixObject().setValue(context, MemberNames.JWKSUri.toString(), jwksuri);
	}

	/**
	 * @return value of Issuer
	 */
	public final java.lang.String getIssuer()
	{
		return getIssuer(getContext());
	}

	/**
	 * @param context
	 * @return value of Issuer
	 */
	public final java.lang.String getIssuer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Issuer.toString());
	}

	/**
	 * Set value of Issuer
	 * @param issuer
	 */
	public final void setIssuer(java.lang.String issuer)
	{
		setIssuer(getContext(), issuer);
	}

	/**
	 * Set value of Issuer
	 * @param context
	 * @param issuer
	 */
	public final void setIssuer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issuer)
	{
		getMendixObject().setValue(context, MemberNames.Issuer.toString(), issuer);
	}

	/**
	 * Set value of ProvisioningFlow
	 * @param provisioningflow
	 */
	public final oidc.proxies.ENU_UserProvisioningFlows getProvisioningFlow()
	{
		return getProvisioningFlow(getContext());
	}

	/**
	 * @param context
	 * @return value of ProvisioningFlow
	 */
	public final oidc.proxies.ENU_UserProvisioningFlows getProvisioningFlow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProvisioningFlow.toString());
		if (obj == null) {
			return null;
		}
		return oidc.proxies.ENU_UserProvisioningFlows.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProvisioningFlow
	 * @param provisioningflow
	 */
	public final void setProvisioningFlow(oidc.proxies.ENU_UserProvisioningFlows provisioningflow)
	{
		setProvisioningFlow(getContext(), provisioningflow);
	}

	/**
	 * Set value of ProvisioningFlow
	 * @param context
	 * @param provisioningflow
	 */
	public final void setProvisioningFlow(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.ENU_UserProvisioningFlows provisioningflow)
	{
		if (provisioningflow != null) {
			getMendixObject().setValue(context, MemberNames.ProvisioningFlow.toString(), provisioningflow.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ProvisioningFlow.toString(), null);
		}
	}

	/**
	 * Set value of ResponseMode
	 * @param responsemode
	 */
	public final oidc.proxies.ENU_ResponseMode getResponseMode()
	{
		return getResponseMode(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseMode
	 */
	public final oidc.proxies.ENU_ResponseMode getResponseMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ResponseMode.toString());
		if (obj == null) {
			return null;
		}
		return oidc.proxies.ENU_ResponseMode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ResponseMode
	 * @param responsemode
	 */
	public final void setResponseMode(oidc.proxies.ENU_ResponseMode responsemode)
	{
		setResponseMode(getContext(), responsemode);
	}

	/**
	 * Set value of ResponseMode
	 * @param context
	 * @param responsemode
	 */
	public final void setResponseMode(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.ENU_ResponseMode responsemode)
	{
		if (responsemode != null) {
			getMendixObject().setValue(context, MemberNames.ResponseMode.toString(), responsemode.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ResponseMode.toString(), null);
		}
	}

	/**
	 * @return value of UsePCKE
	 */
	public final java.lang.Boolean getUsePCKE()
	{
		return getUsePCKE(getContext());
	}

	/**
	 * @param context
	 * @return value of UsePCKE
	 */
	public final java.lang.Boolean getUsePCKE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UsePCKE.toString());
	}

	/**
	 * Set value of UsePCKE
	 * @param usepcke
	 */
	public final void setUsePCKE(java.lang.Boolean usepcke)
	{
		setUsePCKE(getContext(), usepcke);
	}

	/**
	 * Set value of UsePCKE
	 * @param context
	 * @param usepcke
	 */
	public final void setUsePCKE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usepcke)
	{
		getMendixObject().setValue(context, MemberNames.UsePCKE.toString(), usepcke);
	}

	/**
	 * @return value of CustomCallbackURL
	 */
	public final java.lang.String getCustomCallbackURL()
	{
		return getCustomCallbackURL(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomCallbackURL
	 */
	public final java.lang.String getCustomCallbackURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomCallbackURL.toString());
	}

	/**
	 * Set value of CustomCallbackURL
	 * @param customcallbackurl
	 */
	public final void setCustomCallbackURL(java.lang.String customcallbackurl)
	{
		setCustomCallbackURL(getContext(), customcallbackurl);
	}

	/**
	 * Set value of CustomCallbackURL
	 * @param context
	 * @param customcallbackurl
	 */
	public final void setCustomCallbackURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customcallbackurl)
	{
		getMendixObject().setValue(context, MemberNames.CustomCallbackURL.toString(), customcallbackurl);
	}

	/**
	 * @return value of parseroles
	 */
	public final java.lang.Boolean getparseroles()
	{
		return getparseroles(getContext());
	}

	/**
	 * @param context
	 * @return value of parseroles
	 */
	public final java.lang.Boolean getparseroles(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.parseroles.toString());
	}

	/**
	 * Set value of parseroles
	 * @param parseroles
	 */
	public final void setparseroles(java.lang.Boolean parseroles)
	{
		setparseroles(getContext(), parseroles);
	}

	/**
	 * Set value of parseroles
	 * @param context
	 * @param parseroles
	 */
	public final void setparseroles(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean parseroles)
	{
		getMendixObject().setValue(context, MemberNames.parseroles.toString(), parseroles);
	}

	/**
	 * Set value of ClientAuthenticationMethod
	 * @param clientauthenticationmethod
	 */
	public final oidc.proxies.ENU_ClientAuthenticationMethod getClientAuthenticationMethod()
	{
		return getClientAuthenticationMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientAuthenticationMethod
	 */
	public final oidc.proxies.ENU_ClientAuthenticationMethod getClientAuthenticationMethod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ClientAuthenticationMethod.toString());
		if (obj == null) {
			return null;
		}
		return oidc.proxies.ENU_ClientAuthenticationMethod.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ClientAuthenticationMethod
	 * @param clientauthenticationmethod
	 */
	public final void setClientAuthenticationMethod(oidc.proxies.ENU_ClientAuthenticationMethod clientauthenticationmethod)
	{
		setClientAuthenticationMethod(getContext(), clientauthenticationmethod);
	}

	/**
	 * Set value of ClientAuthenticationMethod
	 * @param context
	 * @param clientauthenticationmethod
	 */
	public final void setClientAuthenticationMethod(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.ENU_ClientAuthenticationMethod clientauthenticationmethod)
	{
		if (clientauthenticationmethod != null) {
			getMendixObject().setValue(context, MemberNames.ClientAuthenticationMethod.toString(), clientauthenticationmethod.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ClientAuthenticationMethod.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SelectedScopes
	 */
	public final java.util.List<oidc.proxies.Scope> getSelectedScopes() throws com.mendix.core.CoreException
	{
		return getSelectedScopes(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedScopes
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<oidc.proxies.Scope> getSelectedScopes(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<oidc.proxies.Scope> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.SelectedScopes.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(oidc.proxies.Scope.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of SelectedScopes
	 * @param selectedscopes
	 */
	public final void setSelectedScopes(java.util.List<oidc.proxies.Scope> selectedscopes)
	{
		setSelectedScopes(getContext(), selectedscopes);
	}

	/**
	 * Set value of SelectedScopes
	 * @param context
	 * @param selectedscopes
	 */
	public final void setSelectedScopes(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<oidc.proxies.Scope> selectedscopes)
	{
		var identifiers = selectedscopes
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.SelectedScopes.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ClientConfiguration_ScopeSet
	 */
	public final oidc.proxies.ScopeSet getClientConfiguration_ScopeSet() throws com.mendix.core.CoreException
	{
		return getClientConfiguration_ScopeSet(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientConfiguration_ScopeSet
	 * @throws com.mendix.core.CoreException
	 */
	public final oidc.proxies.ScopeSet getClientConfiguration_ScopeSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oidc.proxies.ScopeSet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ClientConfiguration_ScopeSet.toString());
		if (identifier != null) {
			result = oidc.proxies.ScopeSet.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ClientConfiguration_ScopeSet
	 * @param clientconfiguration_scopeset
	 */
	public final void setClientConfiguration_ScopeSet(oidc.proxies.ScopeSet clientconfiguration_scopeset)
	{
		setClientConfiguration_ScopeSet(getContext(), clientconfiguration_scopeset);
	}

	/**
	 * Set value of ClientConfiguration_ScopeSet
	 * @param context
	 * @param clientconfiguration_scopeset
	 */
	public final void setClientConfiguration_ScopeSet(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.ScopeSet clientconfiguration_scopeset)
	{
		if (clientconfiguration_scopeset == null) {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_ScopeSet.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_ScopeSet.toString(), clientconfiguration_scopeset.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ClientConfiguration_ClaimSet
	 */
	public final oidc.proxies.ClaimSet getClientConfiguration_ClaimSet() throws com.mendix.core.CoreException
	{
		return getClientConfiguration_ClaimSet(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientConfiguration_ClaimSet
	 * @throws com.mendix.core.CoreException
	 */
	public final oidc.proxies.ClaimSet getClientConfiguration_ClaimSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oidc.proxies.ClaimSet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ClientConfiguration_ClaimSet.toString());
		if (identifier != null) {
			result = oidc.proxies.ClaimSet.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ClientConfiguration_ClaimSet
	 * @param clientconfiguration_claimset
	 */
	public final void setClientConfiguration_ClaimSet(oidc.proxies.ClaimSet clientconfiguration_claimset)
	{
		setClientConfiguration_ClaimSet(getContext(), clientconfiguration_claimset);
	}

	/**
	 * Set value of ClientConfiguration_ClaimSet
	 * @param context
	 * @param clientconfiguration_claimset
	 */
	public final void setClientConfiguration_ClaimSet(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.ClaimSet clientconfiguration_claimset)
	{
		if (clientconfiguration_claimset == null) {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_ClaimSet.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_ClaimSet.toString(), clientconfiguration_claimset.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SelectedClaims
	 */
	public final java.util.List<oidc.proxies.Claim> getSelectedClaims() throws com.mendix.core.CoreException
	{
		return getSelectedClaims(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedClaims
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<oidc.proxies.Claim> getSelectedClaims(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<oidc.proxies.Claim> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.SelectedClaims.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(oidc.proxies.Claim.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of SelectedClaims
	 * @param selectedclaims
	 */
	public final void setSelectedClaims(java.util.List<oidc.proxies.Claim> selectedclaims)
	{
		setSelectedClaims(getContext(), selectedclaims);
	}

	/**
	 * Set value of SelectedClaims
	 * @param context
	 * @param selectedclaims
	 */
	public final void setSelectedClaims(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<oidc.proxies.Claim> selectedclaims)
	{
		var identifiers = selectedclaims
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.SelectedClaims.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ClientConfiguration_CodeChallengeMethodsSet
	 */
	public final oidc.proxies.CodeChallengeMethodsSet getClientConfiguration_CodeChallengeMethodsSet() throws com.mendix.core.CoreException
	{
		return getClientConfiguration_CodeChallengeMethodsSet(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientConfiguration_CodeChallengeMethodsSet
	 * @throws com.mendix.core.CoreException
	 */
	public final oidc.proxies.CodeChallengeMethodsSet getClientConfiguration_CodeChallengeMethodsSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oidc.proxies.CodeChallengeMethodsSet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ClientConfiguration_CodeChallengeMethodsSet.toString());
		if (identifier != null) {
			result = oidc.proxies.CodeChallengeMethodsSet.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ClientConfiguration_CodeChallengeMethodsSet
	 * @param clientconfiguration_codechallengemethodsset
	 */
	public final void setClientConfiguration_CodeChallengeMethodsSet(oidc.proxies.CodeChallengeMethodsSet clientconfiguration_codechallengemethodsset)
	{
		setClientConfiguration_CodeChallengeMethodsSet(getContext(), clientconfiguration_codechallengemethodsset);
	}

	/**
	 * Set value of ClientConfiguration_CodeChallengeMethodsSet
	 * @param context
	 * @param clientconfiguration_codechallengemethodsset
	 */
	public final void setClientConfiguration_CodeChallengeMethodsSet(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.CodeChallengeMethodsSet clientconfiguration_codechallengemethodsset)
	{
		if (clientconfiguration_codechallengemethodsset == null) {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_CodeChallengeMethodsSet.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_CodeChallengeMethodsSet.toString(), clientconfiguration_codechallengemethodsset.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ClientConfiguration_CodeChallengeMethods
	 */
	public final java.util.List<oidc.proxies.CodeChallengeMethods> getClientConfiguration_CodeChallengeMethods() throws com.mendix.core.CoreException
	{
		return getClientConfiguration_CodeChallengeMethods(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientConfiguration_CodeChallengeMethods
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<oidc.proxies.CodeChallengeMethods> getClientConfiguration_CodeChallengeMethods(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<oidc.proxies.CodeChallengeMethods> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ClientConfiguration_CodeChallengeMethods.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(oidc.proxies.CodeChallengeMethods.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of ClientConfiguration_CodeChallengeMethods
	 * @param clientconfiguration_codechallengemethods
	 */
	public final void setClientConfiguration_CodeChallengeMethods(java.util.List<oidc.proxies.CodeChallengeMethods> clientconfiguration_codechallengemethods)
	{
		setClientConfiguration_CodeChallengeMethods(getContext(), clientconfiguration_codechallengemethods);
	}

	/**
	 * Set value of ClientConfiguration_CodeChallengeMethods
	 * @param context
	 * @param clientconfiguration_codechallengemethods
	 */
	public final void setClientConfiguration_CodeChallengeMethods(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<oidc.proxies.CodeChallengeMethods> clientconfiguration_codechallengemethods)
	{
		var identifiers = clientconfiguration_codechallengemethods
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.ClientConfiguration_CodeChallengeMethods.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ClientConfiguration_Microflows
	 */
	public final mxmodelreflection.proxies.Microflows getClientConfiguration_Microflows() throws com.mendix.core.CoreException
	{
		return getClientConfiguration_Microflows(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientConfiguration_Microflows
	 * @throws com.mendix.core.CoreException
	 */
	public final mxmodelreflection.proxies.Microflows getClientConfiguration_Microflows(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.Microflows result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ClientConfiguration_Microflows.toString());
		if (identifier != null) {
			result = mxmodelreflection.proxies.Microflows.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ClientConfiguration_Microflows
	 * @param clientconfiguration_microflows
	 */
	public final void setClientConfiguration_Microflows(mxmodelreflection.proxies.Microflows clientconfiguration_microflows)
	{
		setClientConfiguration_Microflows(getContext(), clientconfiguration_microflows);
	}

	/**
	 * Set value of ClientConfiguration_Microflows
	 * @param context
	 * @param clientconfiguration_microflows
	 */
	public final void setClientConfiguration_Microflows(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.Microflows clientconfiguration_microflows)
	{
		if (clientconfiguration_microflows == null) {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_Microflows.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_Microflows.toString(), clientconfiguration_microflows.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return clientConfigurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.ClientConfiguration that = (oidc.proxies.ClientConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
