// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public class OAuthTokenResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject oAuthTokenResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.OAuthTokenResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Access_token("Access_token"),
		Refresh_token("Refresh_token"),
		Instance_url("Instance_url"),
		_id("_id"),
		Id_token("Id_token"),
		Token_type("Token_type"),
		Issued_at("Issued_at"),
		Expires_in("Expires_in"),
		Signature("Signature"),
		Code("Code"),
		State("State"),
		Nonce("Nonce"),
		Scope("Scope");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OAuthTokenResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OAuthTokenResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject oAuthTokenResponseMendixObject)
	{
		if (oAuthTokenResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, oAuthTokenResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.oAuthTokenResponseMendixObject = oAuthTokenResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OAuthTokenResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.OAuthTokenResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.OAuthTokenResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.OAuthTokenResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.OAuthTokenResponse(context, mendixObject);
	}

	public static oidc.proxies.OAuthTokenResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.OAuthTokenResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	/**
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token()
	{
		return getRefresh_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Refresh_token.toString());
	}

	/**
	 * Set value of Refresh_token
	 * @param refresh_token
	 */
	public final void setRefresh_token(java.lang.String refresh_token)
	{
		setRefresh_token(getContext(), refresh_token);
	}

	/**
	 * Set value of Refresh_token
	 * @param context
	 * @param refresh_token
	 */
	public final void setRefresh_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refresh_token)
	{
		getMendixObject().setValue(context, MemberNames.Refresh_token.toString(), refresh_token);
	}

	/**
	 * @return value of Instance_url
	 */
	public final java.lang.String getInstance_url()
	{
		return getInstance_url(getContext());
	}

	/**
	 * @param context
	 * @return value of Instance_url
	 */
	public final java.lang.String getInstance_url(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Instance_url.toString());
	}

	/**
	 * Set value of Instance_url
	 * @param instance_url
	 */
	public final void setInstance_url(java.lang.String instance_url)
	{
		setInstance_url(getContext(), instance_url);
	}

	/**
	 * Set value of Instance_url
	 * @param context
	 * @param instance_url
	 */
	public final void setInstance_url(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instance_url)
	{
		getMendixObject().setValue(context, MemberNames.Instance_url.toString(), instance_url);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Id_token
	 */
	public final java.lang.String getId_token()
	{
		return getId_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Id_token
	 */
	public final java.lang.String getId_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Id_token.toString());
	}

	/**
	 * Set value of Id_token
	 * @param id_token
	 */
	public final void setId_token(java.lang.String id_token)
	{
		setId_token(getContext(), id_token);
	}

	/**
	 * Set value of Id_token
	 * @param context
	 * @param id_token
	 */
	public final void setId_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String id_token)
	{
		getMendixObject().setValue(context, MemberNames.Id_token.toString(), id_token);
	}

	/**
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type()
	{
		return getToken_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_type.toString());
	}

	/**
	 * Set value of Token_type
	 * @param token_type
	 */
	public final void setToken_type(java.lang.String token_type)
	{
		setToken_type(getContext(), token_type);
	}

	/**
	 * Set value of Token_type
	 * @param context
	 * @param token_type
	 */
	public final void setToken_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.Token_type.toString(), token_type);
	}

	/**
	 * @return value of Issued_at
	 */
	public final java.lang.String getIssued_at()
	{
		return getIssued_at(getContext());
	}

	/**
	 * @param context
	 * @return value of Issued_at
	 */
	public final java.lang.String getIssued_at(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Issued_at.toString());
	}

	/**
	 * Set value of Issued_at
	 * @param issued_at
	 */
	public final void setIssued_at(java.lang.String issued_at)
	{
		setIssued_at(getContext(), issued_at);
	}

	/**
	 * Set value of Issued_at
	 * @param context
	 * @param issued_at
	 */
	public final void setIssued_at(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issued_at)
	{
		getMendixObject().setValue(context, MemberNames.Issued_at.toString(), issued_at);
	}

	/**
	 * @return value of Expires_in
	 */
	public final java.lang.Integer getExpires_in()
	{
		return getExpires_in(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_in
	 */
	public final java.lang.Integer getExpires_in(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Expires_in.toString());
	}

	/**
	 * Set value of Expires_in
	 * @param expires_in
	 */
	public final void setExpires_in(java.lang.Integer expires_in)
	{
		setExpires_in(getContext(), expires_in);
	}

	/**
	 * Set value of Expires_in
	 * @param context
	 * @param expires_in
	 */
	public final void setExpires_in(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer expires_in)
	{
		getMendixObject().setValue(context, MemberNames.Expires_in.toString(), expires_in);
	}

	/**
	 * @return value of Signature
	 */
	public final java.lang.String getSignature()
	{
		return getSignature(getContext());
	}

	/**
	 * @param context
	 * @return value of Signature
	 */
	public final java.lang.String getSignature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Signature.toString());
	}

	/**
	 * Set value of Signature
	 * @param signature
	 */
	public final void setSignature(java.lang.String signature)
	{
		setSignature(getContext(), signature);
	}

	/**
	 * Set value of Signature
	 * @param context
	 * @param signature
	 */
	public final void setSignature(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String signature)
	{
		getMendixObject().setValue(context, MemberNames.Signature.toString(), signature);
	}

	/**
	 * @return value of Code
	 */
	public final java.lang.String getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.String getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.String code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of Nonce
	 */
	public final java.lang.String getNonce()
	{
		return getNonce(getContext());
	}

	/**
	 * @param context
	 * @return value of Nonce
	 */
	public final java.lang.String getNonce(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nonce.toString());
	}

	/**
	 * Set value of Nonce
	 * @param nonce
	 */
	public final void setNonce(java.lang.String nonce)
	{
		setNonce(getContext(), nonce);
	}

	/**
	 * Set value of Nonce
	 * @param context
	 * @param nonce
	 */
	public final void setNonce(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nonce)
	{
		getMendixObject().setValue(context, MemberNames.Nonce.toString(), nonce);
	}

	/**
	 * @return value of Scope
	 */
	public final java.lang.String getScope()
	{
		return getScope(getContext());
	}

	/**
	 * @param context
	 * @return value of Scope
	 */
	public final java.lang.String getScope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Scope.toString());
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final void setScope(java.lang.String scope)
	{
		setScope(getContext(), scope);
	}

	/**
	 * Set value of Scope
	 * @param context
	 * @param scope
	 */
	public final void setScope(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scope)
	{
		getMendixObject().setValue(context, MemberNames.Scope.toString(), scope);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return oAuthTokenResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.OAuthTokenResponse that = (oidc.proxies.OAuthTokenResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
