// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public class OIDCToken
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject oIDCTokenMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.OIDCToken";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Zoneinfo("Zoneinfo"),
		Preferred_username("Preferred_username"),
		Locale("Locale"),
		Name("Name"),
		Email("Email"),
		Sub("Sub"),
		Email_verified("Email_verified"),
		Given_name("Given_name"),
		Family_name("Family_name"),
		Phone_number("Phone_number"),
		Profile("Profile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OIDCToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OIDCToken(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject oIDCTokenMendixObject)
	{
		if (oIDCTokenMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, oIDCTokenMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.oIDCTokenMendixObject = oIDCTokenMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OIDCToken.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.OIDCToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.OIDCToken.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.OIDCToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.OIDCToken(context, mendixObject);
	}

	public static oidc.proxies.OIDCToken load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.OIDCToken.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Zoneinfo
	 */
	public final java.lang.String getZoneinfo()
	{
		return getZoneinfo(getContext());
	}

	/**
	 * @param context
	 * @return value of Zoneinfo
	 */
	public final java.lang.String getZoneinfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Zoneinfo.toString());
	}

	/**
	 * Set value of Zoneinfo
	 * @param zoneinfo
	 */
	public final void setZoneinfo(java.lang.String zoneinfo)
	{
		setZoneinfo(getContext(), zoneinfo);
	}

	/**
	 * Set value of Zoneinfo
	 * @param context
	 * @param zoneinfo
	 */
	public final void setZoneinfo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zoneinfo)
	{
		getMendixObject().setValue(context, MemberNames.Zoneinfo.toString(), zoneinfo);
	}

	/**
	 * @return value of Preferred_username
	 */
	public final java.lang.String getPreferred_username()
	{
		return getPreferred_username(getContext());
	}

	/**
	 * @param context
	 * @return value of Preferred_username
	 */
	public final java.lang.String getPreferred_username(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Preferred_username.toString());
	}

	/**
	 * Set value of Preferred_username
	 * @param preferred_username
	 */
	public final void setPreferred_username(java.lang.String preferred_username)
	{
		setPreferred_username(getContext(), preferred_username);
	}

	/**
	 * Set value of Preferred_username
	 * @param context
	 * @param preferred_username
	 */
	public final void setPreferred_username(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String preferred_username)
	{
		getMendixObject().setValue(context, MemberNames.Preferred_username.toString(), preferred_username);
	}

	/**
	 * @return value of Locale
	 */
	public final java.lang.String getLocale()
	{
		return getLocale(getContext());
	}

	/**
	 * @param context
	 * @return value of Locale
	 */
	public final java.lang.String getLocale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Locale.toString());
	}

	/**
	 * Set value of Locale
	 * @param locale
	 */
	public final void setLocale(java.lang.String locale)
	{
		setLocale(getContext(), locale);
	}

	/**
	 * Set value of Locale
	 * @param context
	 * @param locale
	 */
	public final void setLocale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locale)
	{
		getMendixObject().setValue(context, MemberNames.Locale.toString(), locale);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Sub
	 */
	public final java.lang.String getSub()
	{
		return getSub(getContext());
	}

	/**
	 * @param context
	 * @return value of Sub
	 */
	public final java.lang.String getSub(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sub.toString());
	}

	/**
	 * Set value of Sub
	 * @param sub
	 */
	public final void setSub(java.lang.String sub)
	{
		setSub(getContext(), sub);
	}

	/**
	 * Set value of Sub
	 * @param context
	 * @param sub
	 */
	public final void setSub(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sub)
	{
		getMendixObject().setValue(context, MemberNames.Sub.toString(), sub);
	}

	/**
	 * @return value of Email_verified
	 */
	public final java.lang.Boolean getEmail_verified()
	{
		return getEmail_verified(getContext());
	}

	/**
	 * @param context
	 * @return value of Email_verified
	 */
	public final java.lang.Boolean getEmail_verified(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Email_verified.toString());
	}

	/**
	 * Set value of Email_verified
	 * @param email_verified
	 */
	public final void setEmail_verified(java.lang.Boolean email_verified)
	{
		setEmail_verified(getContext(), email_verified);
	}

	/**
	 * Set value of Email_verified
	 * @param context
	 * @param email_verified
	 */
	public final void setEmail_verified(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean email_verified)
	{
		getMendixObject().setValue(context, MemberNames.Email_verified.toString(), email_verified);
	}

	/**
	 * @return value of Given_name
	 */
	public final java.lang.String getGiven_name()
	{
		return getGiven_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Given_name
	 */
	public final java.lang.String getGiven_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Given_name.toString());
	}

	/**
	 * Set value of Given_name
	 * @param given_name
	 */
	public final void setGiven_name(java.lang.String given_name)
	{
		setGiven_name(getContext(), given_name);
	}

	/**
	 * Set value of Given_name
	 * @param context
	 * @param given_name
	 */
	public final void setGiven_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String given_name)
	{
		getMendixObject().setValue(context, MemberNames.Given_name.toString(), given_name);
	}

	/**
	 * @return value of Family_name
	 */
	public final java.lang.String getFamily_name()
	{
		return getFamily_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Family_name
	 */
	public final java.lang.String getFamily_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Family_name.toString());
	}

	/**
	 * Set value of Family_name
	 * @param family_name
	 */
	public final void setFamily_name(java.lang.String family_name)
	{
		setFamily_name(getContext(), family_name);
	}

	/**
	 * Set value of Family_name
	 * @param context
	 * @param family_name
	 */
	public final void setFamily_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String family_name)
	{
		getMendixObject().setValue(context, MemberNames.Family_name.toString(), family_name);
	}

	/**
	 * @return value of Phone_number
	 */
	public final java.lang.String getPhone_number()
	{
		return getPhone_number(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone_number
	 */
	public final java.lang.String getPhone_number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone_number.toString());
	}

	/**
	 * Set value of Phone_number
	 * @param phone_number
	 */
	public final void setPhone_number(java.lang.String phone_number)
	{
		setPhone_number(getContext(), phone_number);
	}

	/**
	 * Set value of Phone_number
	 * @param context
	 * @param phone_number
	 */
	public final void setPhone_number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone_number)
	{
		getMendixObject().setValue(context, MemberNames.Phone_number.toString(), phone_number);
	}

	/**
	 * @return value of Profile
	 */
	public final java.lang.String getProfile()
	{
		return getProfile(getContext());
	}

	/**
	 * @param context
	 * @return value of Profile
	 */
	public final java.lang.String getProfile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Profile.toString());
	}

	/**
	 * Set value of Profile
	 * @param profile
	 */
	public final void setProfile(java.lang.String profile)
	{
		setProfile(getContext(), profile);
	}

	/**
	 * Set value of Profile
	 * @param context
	 * @param profile
	 */
	public final void setProfile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String profile)
	{
		getMendixObject().setValue(context, MemberNames.Profile.toString(), profile);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return oIDCTokenMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.OIDCToken that = (oidc.proxies.OIDCToken) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
