// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public class Photos
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject photosMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.Photos";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Picture("Picture"),
		Thumbnail("Thumbnail"),
		Photos_Salesforce_UserInfo("OIDC.Photos_Salesforce_UserInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Photos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Photos(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject photosMendixObject)
	{
		if (photosMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, photosMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.photosMendixObject = photosMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Photos.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.Photos initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.Photos.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.Photos initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.Photos(context, mendixObject);
	}

	public static oidc.proxies.Photos load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.Photos.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Picture
	 */
	public final java.lang.String getPicture()
	{
		return getPicture(getContext());
	}

	/**
	 * @param context
	 * @return value of Picture
	 */
	public final java.lang.String getPicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Picture.toString());
	}

	/**
	 * Set value of Picture
	 * @param picture
	 */
	public final void setPicture(java.lang.String picture)
	{
		setPicture(getContext(), picture);
	}

	/**
	 * Set value of Picture
	 * @param context
	 * @param picture
	 */
	public final void setPicture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String picture)
	{
		getMendixObject().setValue(context, MemberNames.Picture.toString(), picture);
	}

	/**
	 * @return value of Thumbnail
	 */
	public final java.lang.String getThumbnail()
	{
		return getThumbnail(getContext());
	}

	/**
	 * @param context
	 * @return value of Thumbnail
	 */
	public final java.lang.String getThumbnail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Thumbnail.toString());
	}

	/**
	 * Set value of Thumbnail
	 * @param thumbnail
	 */
	public final void setThumbnail(java.lang.String thumbnail)
	{
		setThumbnail(getContext(), thumbnail);
	}

	/**
	 * Set value of Thumbnail
	 * @param context
	 * @param thumbnail
	 */
	public final void setThumbnail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String thumbnail)
	{
		getMendixObject().setValue(context, MemberNames.Thumbnail.toString(), thumbnail);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Photos_Salesforce_UserInfo
	 */
	public final oidc.proxies.Salesforce_UserInfo getPhotos_Salesforce_UserInfo() throws com.mendix.core.CoreException
	{
		return getPhotos_Salesforce_UserInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of Photos_Salesforce_UserInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final oidc.proxies.Salesforce_UserInfo getPhotos_Salesforce_UserInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oidc.proxies.Salesforce_UserInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Photos_Salesforce_UserInfo.toString());
		if (identifier != null) {
			result = oidc.proxies.Salesforce_UserInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Photos_Salesforce_UserInfo
	 * @param photos_salesforce_userinfo
	 */
	public final void setPhotos_Salesforce_UserInfo(oidc.proxies.Salesforce_UserInfo photos_salesforce_userinfo)
	{
		setPhotos_Salesforce_UserInfo(getContext(), photos_salesforce_userinfo);
	}

	/**
	 * Set value of Photos_Salesforce_UserInfo
	 * @param context
	 * @param photos_salesforce_userinfo
	 */
	public final void setPhotos_Salesforce_UserInfo(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.Salesforce_UserInfo photos_salesforce_userinfo)
	{
		if (photos_salesforce_userinfo == null) {
			getMendixObject().setValue(context, MemberNames.Photos_Salesforce_UserInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Photos_Salesforce_UserInfo.toString(), photos_salesforce_userinfo.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return photosMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.Photos that = (oidc.proxies.Photos) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
