// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public class Salesforce_UserInfo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject salesforce_UserInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.Salesforce_UserInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Asserted_user("Asserted_user"),
		User_id("User_id"),
		Organization_id("Organization_id"),
		Username("Username"),
		Nick_name("Nick_name"),
		Display_name("Display_name"),
		Email("Email"),
		Email_verified("Email_verified"),
		First_name("First_name"),
		Last_name("Last_name"),
		Active("Active"),
		Language("Language"),
		Locale("Locale"),
		UtcOffset("UtcOffset"),
		Photos_Salesforce_UserInfo("OIDC.Photos_Salesforce_UserInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Salesforce_UserInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Salesforce_UserInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesforce_UserInfoMendixObject)
	{
		if (salesforce_UserInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, salesforce_UserInfoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.salesforce_UserInfoMendixObject = salesforce_UserInfoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Salesforce_UserInfo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.Salesforce_UserInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.Salesforce_UserInfo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.Salesforce_UserInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.Salesforce_UserInfo(context, mendixObject);
	}

	public static oidc.proxies.Salesforce_UserInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.Salesforce_UserInfo.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Asserted_user
	 */
	public final java.lang.Boolean getAsserted_user()
	{
		return getAsserted_user(getContext());
	}

	/**
	 * @param context
	 * @return value of Asserted_user
	 */
	public final java.lang.Boolean getAsserted_user(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Asserted_user.toString());
	}

	/**
	 * Set value of Asserted_user
	 * @param asserted_user
	 */
	public final void setAsserted_user(java.lang.Boolean asserted_user)
	{
		setAsserted_user(getContext(), asserted_user);
	}

	/**
	 * Set value of Asserted_user
	 * @param context
	 * @param asserted_user
	 */
	public final void setAsserted_user(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean asserted_user)
	{
		getMendixObject().setValue(context, MemberNames.Asserted_user.toString(), asserted_user);
	}

	/**
	 * @return value of User_id
	 */
	public final java.lang.String getUser_id()
	{
		return getUser_id(getContext());
	}

	/**
	 * @param context
	 * @return value of User_id
	 */
	public final java.lang.String getUser_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User_id.toString());
	}

	/**
	 * Set value of User_id
	 * @param user_id
	 */
	public final void setUser_id(java.lang.String user_id)
	{
		setUser_id(getContext(), user_id);
	}

	/**
	 * Set value of User_id
	 * @param context
	 * @param user_id
	 */
	public final void setUser_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user_id)
	{
		getMendixObject().setValue(context, MemberNames.User_id.toString(), user_id);
	}

	/**
	 * @return value of Organization_id
	 */
	public final java.lang.String getOrganization_id()
	{
		return getOrganization_id(getContext());
	}

	/**
	 * @param context
	 * @return value of Organization_id
	 */
	public final java.lang.String getOrganization_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Organization_id.toString());
	}

	/**
	 * Set value of Organization_id
	 * @param organization_id
	 */
	public final void setOrganization_id(java.lang.String organization_id)
	{
		setOrganization_id(getContext(), organization_id);
	}

	/**
	 * Set value of Organization_id
	 * @param context
	 * @param organization_id
	 */
	public final void setOrganization_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organization_id)
	{
		getMendixObject().setValue(context, MemberNames.Organization_id.toString(), organization_id);
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Nick_name
	 */
	public final java.lang.String getNick_name()
	{
		return getNick_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Nick_name
	 */
	public final java.lang.String getNick_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nick_name.toString());
	}

	/**
	 * Set value of Nick_name
	 * @param nick_name
	 */
	public final void setNick_name(java.lang.String nick_name)
	{
		setNick_name(getContext(), nick_name);
	}

	/**
	 * Set value of Nick_name
	 * @param context
	 * @param nick_name
	 */
	public final void setNick_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nick_name)
	{
		getMendixObject().setValue(context, MemberNames.Nick_name.toString(), nick_name);
	}

	/**
	 * @return value of Display_name
	 */
	public final java.lang.String getDisplay_name()
	{
		return getDisplay_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Display_name
	 */
	public final java.lang.String getDisplay_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Display_name.toString());
	}

	/**
	 * Set value of Display_name
	 * @param display_name
	 */
	public final void setDisplay_name(java.lang.String display_name)
	{
		setDisplay_name(getContext(), display_name);
	}

	/**
	 * Set value of Display_name
	 * @param context
	 * @param display_name
	 */
	public final void setDisplay_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String display_name)
	{
		getMendixObject().setValue(context, MemberNames.Display_name.toString(), display_name);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Email_verified
	 */
	public final java.lang.Boolean getEmail_verified()
	{
		return getEmail_verified(getContext());
	}

	/**
	 * @param context
	 * @return value of Email_verified
	 */
	public final java.lang.Boolean getEmail_verified(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Email_verified.toString());
	}

	/**
	 * Set value of Email_verified
	 * @param email_verified
	 */
	public final void setEmail_verified(java.lang.Boolean email_verified)
	{
		setEmail_verified(getContext(), email_verified);
	}

	/**
	 * Set value of Email_verified
	 * @param context
	 * @param email_verified
	 */
	public final void setEmail_verified(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean email_verified)
	{
		getMendixObject().setValue(context, MemberNames.Email_verified.toString(), email_verified);
	}

	/**
	 * @return value of First_name
	 */
	public final java.lang.String getFirst_name()
	{
		return getFirst_name(getContext());
	}

	/**
	 * @param context
	 * @return value of First_name
	 */
	public final java.lang.String getFirst_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.First_name.toString());
	}

	/**
	 * Set value of First_name
	 * @param first_name
	 */
	public final void setFirst_name(java.lang.String first_name)
	{
		setFirst_name(getContext(), first_name);
	}

	/**
	 * Set value of First_name
	 * @param context
	 * @param first_name
	 */
	public final void setFirst_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String first_name)
	{
		getMendixObject().setValue(context, MemberNames.First_name.toString(), first_name);
	}

	/**
	 * @return value of Last_name
	 */
	public final java.lang.String getLast_name()
	{
		return getLast_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Last_name
	 */
	public final java.lang.String getLast_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Last_name.toString());
	}

	/**
	 * Set value of Last_name
	 * @param last_name
	 */
	public final void setLast_name(java.lang.String last_name)
	{
		setLast_name(getContext(), last_name);
	}

	/**
	 * Set value of Last_name
	 * @param context
	 * @param last_name
	 */
	public final void setLast_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String last_name)
	{
		getMendixObject().setValue(context, MemberNames.Last_name.toString(), last_name);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of Language
	 */
	public final java.lang.String getLanguage()
	{
		return getLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of Language
	 */
	public final java.lang.String getLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Language.toString());
	}

	/**
	 * Set value of Language
	 * @param language
	 */
	public final void setLanguage(java.lang.String language)
	{
		setLanguage(getContext(), language);
	}

	/**
	 * Set value of Language
	 * @param context
	 * @param language
	 */
	public final void setLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String language)
	{
		getMendixObject().setValue(context, MemberNames.Language.toString(), language);
	}

	/**
	 * @return value of Locale
	 */
	public final java.lang.String getLocale()
	{
		return getLocale(getContext());
	}

	/**
	 * @param context
	 * @return value of Locale
	 */
	public final java.lang.String getLocale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Locale.toString());
	}

	/**
	 * Set value of Locale
	 * @param locale
	 */
	public final void setLocale(java.lang.String locale)
	{
		setLocale(getContext(), locale);
	}

	/**
	 * Set value of Locale
	 * @param context
	 * @param locale
	 */
	public final void setLocale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locale)
	{
		getMendixObject().setValue(context, MemberNames.Locale.toString(), locale);
	}

	/**
	 * @return value of UtcOffset
	 */
	public final java.lang.Integer getUtcOffset()
	{
		return getUtcOffset(getContext());
	}

	/**
	 * @param context
	 * @return value of UtcOffset
	 */
	public final java.lang.Integer getUtcOffset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.UtcOffset.toString());
	}

	/**
	 * Set value of UtcOffset
	 * @param utcoffset
	 */
	public final void setUtcOffset(java.lang.Integer utcoffset)
	{
		setUtcOffset(getContext(), utcoffset);
	}

	/**
	 * Set value of UtcOffset
	 * @param context
	 * @param utcoffset
	 */
	public final void setUtcOffset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer utcoffset)
	{
		getMendixObject().setValue(context, MemberNames.UtcOffset.toString(), utcoffset);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Photos_Salesforce_UserInfo
	 */
	public final oidc.proxies.Photos getPhotos_Salesforce_UserInfo() throws com.mendix.core.CoreException
	{
		return getPhotos_Salesforce_UserInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of Photos_Salesforce_UserInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final oidc.proxies.Photos getPhotos_Salesforce_UserInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oidc.proxies.Photos result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Photos_Salesforce_UserInfo.toString());
		if (identifier != null) {
			result = oidc.proxies.Photos.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Photos_Salesforce_UserInfo
	 * @param photos_salesforce_userinfo
	 */
	public final void setPhotos_Salesforce_UserInfo(oidc.proxies.Photos photos_salesforce_userinfo)
	{
		setPhotos_Salesforce_UserInfo(getContext(), photos_salesforce_userinfo);
	}

	/**
	 * Set value of Photos_Salesforce_UserInfo
	 * @param context
	 * @param photos_salesforce_userinfo
	 */
	public final void setPhotos_Salesforce_UserInfo(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.Photos photos_salesforce_userinfo)
	{
		if (photos_salesforce_userinfo == null) {
			getMendixObject().setValue(context, MemberNames.Photos_Salesforce_UserInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Photos_Salesforce_UserInfo.toString(), photos_salesforce_userinfo.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return salesforce_UserInfoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.Salesforce_UserInfo that = (oidc.proxies.Salesforce_UserInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
