// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public class SupportedClaim
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject supportedClaimMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.SupportedClaim";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		SupportedClaim_AutoConfigResponse("OIDC.SupportedClaim_AutoConfigResponse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SupportedClaim(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SupportedClaim(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject supportedClaimMendixObject)
	{
		if (supportedClaimMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, supportedClaimMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.supportedClaimMendixObject = supportedClaimMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SupportedClaim.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.SupportedClaim initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.SupportedClaim.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.SupportedClaim initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.SupportedClaim(context, mendixObject);
	}

	public static oidc.proxies.SupportedClaim load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.SupportedClaim.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SupportedClaim_AutoConfigResponse
	 */
	public final oidc.proxies.AutoConfigResponse getSupportedClaim_AutoConfigResponse() throws com.mendix.core.CoreException
	{
		return getSupportedClaim_AutoConfigResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportedClaim_AutoConfigResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final oidc.proxies.AutoConfigResponse getSupportedClaim_AutoConfigResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oidc.proxies.AutoConfigResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SupportedClaim_AutoConfigResponse.toString());
		if (identifier != null) {
			result = oidc.proxies.AutoConfigResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SupportedClaim_AutoConfigResponse
	 * @param supportedclaim_autoconfigresponse
	 */
	public final void setSupportedClaim_AutoConfigResponse(oidc.proxies.AutoConfigResponse supportedclaim_autoconfigresponse)
	{
		setSupportedClaim_AutoConfigResponse(getContext(), supportedclaim_autoconfigresponse);
	}

	/**
	 * Set value of SupportedClaim_AutoConfigResponse
	 * @param context
	 * @param supportedclaim_autoconfigresponse
	 */
	public final void setSupportedClaim_AutoConfigResponse(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.AutoConfigResponse supportedclaim_autoconfigresponse)
	{
		if (supportedclaim_autoconfigresponse == null) {
			getMendixObject().setValue(context, MemberNames.SupportedClaim_AutoConfigResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SupportedClaim_AutoConfigResponse.toString(), supportedclaim_autoconfigresponse.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return supportedClaimMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.SupportedClaim that = (oidc.proxies.SupportedClaim) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
