// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

/**
 * An OAuth access token granted by the OIDC provider via the associated ClientConfiguration object.
 */
public class Token
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tokenMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OIDC.Token";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Access_token("Access_token"),
		Refresh_token("Refresh_token"),
		_id("_id"),
		Id_token("Id_token"),
		Token_type("Token_type"),
		Expires_in("Expires_in"),
		Token_ClientConfiguration("OIDC.Token_ClientConfiguration"),
		Token_User("OIDC.Token_User");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Token(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tokenMendixObject)
	{
		if (tokenMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, tokenMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tokenMendixObject = tokenMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Token.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oidc.proxies.Token initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oidc.proxies.Token.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oidc.proxies.Token initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oidc.proxies.Token(context, mendixObject);
	}

	public static oidc.proxies.Token load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oidc.proxies.Token.initialize(context, mendixObject);
	}

	public static java.util.List<oidc.proxies.Token> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> oidc.proxies.Token.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	/**
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token()
	{
		return getRefresh_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Refresh_token.toString());
	}

	/**
	 * Set value of Refresh_token
	 * @param refresh_token
	 */
	public final void setRefresh_token(java.lang.String refresh_token)
	{
		setRefresh_token(getContext(), refresh_token);
	}

	/**
	 * Set value of Refresh_token
	 * @param context
	 * @param refresh_token
	 */
	public final void setRefresh_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refresh_token)
	{
		getMendixObject().setValue(context, MemberNames.Refresh_token.toString(), refresh_token);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Id_token
	 */
	public final java.lang.String getId_token()
	{
		return getId_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Id_token
	 */
	public final java.lang.String getId_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Id_token.toString());
	}

	/**
	 * Set value of Id_token
	 * @param id_token
	 */
	public final void setId_token(java.lang.String id_token)
	{
		setId_token(getContext(), id_token);
	}

	/**
	 * Set value of Id_token
	 * @param context
	 * @param id_token
	 */
	public final void setId_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String id_token)
	{
		getMendixObject().setValue(context, MemberNames.Id_token.toString(), id_token);
	}

	/**
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type()
	{
		return getToken_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_type.toString());
	}

	/**
	 * Set value of Token_type
	 * @param token_type
	 */
	public final void setToken_type(java.lang.String token_type)
	{
		setToken_type(getContext(), token_type);
	}

	/**
	 * Set value of Token_type
	 * @param context
	 * @param token_type
	 */
	public final void setToken_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.Token_type.toString(), token_type);
	}

	/**
	 * @return value of Expires_in
	 */
	public final java.lang.Integer getExpires_in()
	{
		return getExpires_in(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_in
	 */
	public final java.lang.Integer getExpires_in(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Expires_in.toString());
	}

	/**
	 * Set value of Expires_in
	 * @param expires_in
	 */
	public final void setExpires_in(java.lang.Integer expires_in)
	{
		setExpires_in(getContext(), expires_in);
	}

	/**
	 * Set value of Expires_in
	 * @param context
	 * @param expires_in
	 */
	public final void setExpires_in(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer expires_in)
	{
		getMendixObject().setValue(context, MemberNames.Expires_in.toString(), expires_in);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Token_ClientConfiguration
	 */
	public final oidc.proxies.ClientConfiguration getToken_ClientConfiguration() throws com.mendix.core.CoreException
	{
		return getToken_ClientConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_ClientConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final oidc.proxies.ClientConfiguration getToken_ClientConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oidc.proxies.ClientConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Token_ClientConfiguration.toString());
		if (identifier != null) {
			result = oidc.proxies.ClientConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Token_ClientConfiguration
	 * @param token_clientconfiguration
	 */
	public final void setToken_ClientConfiguration(oidc.proxies.ClientConfiguration token_clientconfiguration)
	{
		setToken_ClientConfiguration(getContext(), token_clientconfiguration);
	}

	/**
	 * Set value of Token_ClientConfiguration
	 * @param context
	 * @param token_clientconfiguration
	 */
	public final void setToken_ClientConfiguration(com.mendix.systemwideinterfaces.core.IContext context, oidc.proxies.ClientConfiguration token_clientconfiguration)
	{
		if (token_clientconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.Token_ClientConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Token_ClientConfiguration.toString(), token_clientconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Token_User
	 */
	public final system.proxies.User getToken_User() throws com.mendix.core.CoreException
	{
		return getToken_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_User
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.User getToken_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Token_User.toString());
		if (identifier != null) {
			result = system.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Token_User
	 * @param token_user
	 */
	public final void setToken_User(system.proxies.User token_user)
	{
		setToken_User(getContext(), token_user);
	}

	/**
	 * Set value of Token_User
	 * @param context
	 * @param token_user
	 */
	public final void setToken_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User token_user)
	{
		if (token_user == null) {
			getMendixObject().setValue(context, MemberNames.Token_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Token_User.toString(), token_user.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tokenMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oidc.proxies.Token that = (oidc.proxies.Token) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
